server:
      port : 8088
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      properties:
          hibernate:
            format_sql: true


